VM Snapshot with checkpoint
Signed-off-by: Anton Todorov <a.todorov@storpool.com>

diff --git a/vmm/kvm/snapshot_create-storpool b/vmm/kvm/snapshot_create-storpool
--- a/vmm/kvm/snapshot_create-storpool
+++ b/vmm/kvm/snapshot_create-storpool
@@ -80,6 +80,93 @@ if boolTrue "VMSNAPSHOT_OVERRIDE"; then
     fi
     ts=$(date +%s)
     res="${VMSNAPSHOT_TAG}-${SNAP_ID}-${ts}"
+    for volume in $vmVolumes; do
+        snap="${volume}-${res}"
+        list+=($volume $snap)
+    done
+    if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
+        # get guest memory
+        rCMD=$(cat <<EOF
+    [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+    virsh --connect \$LIBVIRT_URI dumpxml "$DOMAIN"
+EOF
+)
+        domXML="$($SSH "$VMHOST" "$rCMD")"
+        domMem=$(echo "$domXML" | xmlstarlet sel -t -v domain/memory)
+        MEM_VOL="${ONE_PX}-sys-${VM_ID}"
+        storpoolVolumeCreate "$MEM_VOL" "$((domMem * 2))K" "${ONE_PX}-ds-${VM_DS_ID}"
+        RET=$?
+        if [ $RET -ne 0 ]; then
+            splog "Can't create checkpoint volume! Domain memory ${domMem}K"
+        fi
+        storpoolVolumeAttach "$MEM_VOL" "$VMHOST"
+        if [ $RET -ne 0 ]; then
+            splog "Can't attach checkpoint volume to $VMHOST!"
+        fi
+        list+=($MEM_VOL ${MEM_VOL}-$res)
+        json="$(volumesGroupSnapshotJson "tag:$VM_TAG=$VM_ID" ${list[@]})"
+        apiCmd="$(storpoolApiCmdline=1 storpoolApi "VolumesGroupSnapshot" "$json")"
+        MEM_LNK="/dev/storpool/$MEM_VOL"
+        TDIR="$(mktemp -d)"
+        trapAdd "rm -rf $TDIR"
+        VM_XML="$TDIR/one-${VM_ID}.XML"
+        rCMD=$(cat <<EOF
+ mkdir "$TDIR"
+ RET=\$?
+ logger -t "${0##*/}_r[$$]" -- "mkdir $TDIR(\$RET)"
+ [ \$RET -eq 0 ] || exit \$RET
+ [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+ virsh --connect \$LIBVIRT_URI save "$DOMAIN" "$MEM_LNK"
+ RET=\$?
+ logger -t "${0##*/}_r[$$]" -- "virsh save "$DOMAIN" "$MEM_LNK" (\$RET)"
+ [ \$RET -eq 0 ] || exit \$RET
+ virsh --connect \$LIBVIRT_URI save-image-dumpxml "$MEM_LNK" >"$VM_XML"
+ RET=\$?
+ logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml $MEM_LNK >$VM_XML (\$RET)"
+ [ \$RET -eq 0 ] || exit \$RET
+ $apiCmd >"$TDIR/curl.out" 2>"$TDIR/curl.err"
+ RET=\$?
+ APIRET=42
+ logger -t "${0##*/}_r[$$]" -- "volumeGroupSnapshot (\$RET) \$(cat "$TDIR/curl.out")"
+ if [ \$RET -eq 0 ]; then
+   OK=\$(jq -r '.data.ok' "$TDIR/curl.out" 2>/dev/null)
+   if [ "\$OK" = "true" ]; then
+     APIRET=0
+   else
+     logger -t "${0##*/}_r[$$]" -- "Error: OK='\$OK'"
+   fi
+ else
+   logger -t "${0##*/}_r[$$]" -- "Curl error: \$(cat "$TDIR/curl.err")"
+   exit \$RET
+ fi
+ for i in 0 1 2; do
+   virsh --connect \$LIBVIRT_URI restore "$MEM_LNK" --xml $VM_XML &>>/tmp/one-${VM_ID}-\$i.log
+   RET=\$?
+   logger -t "${0##*/}_r[$$]" -- "[\$i] virsh restore $MEM_LNK --xml $VM_XML (\$RET)"
+   [ \$RET -ne 0 ] || break
+   sleep 0.5
+ done
+ logger -t "${0##*/}_r[$$]" -- "END $VM_ID (\$APIRET::\$RET)"
+ rm -rf "$TDIR"
+ exit \$((RET + APIRET))
+EOF
+)
+        if $SSH "$VMHOST" "$rCMD" >"$TDIR/ssh.out" 2>"$TDIR/ssh.err"; then
+            splog "OK ssh $VMHOST ($?)"
+            RET=0
+        else
+            splog "ssh $VMHOST failed! ($?)"
+            splog "DEBUG_OUT:$(cat "$TDIR/ssh.out")"
+            splog "DEBUG_ERR:$(cat "$TDIR/ssh.err")"
+            RET=1
+        fi
+        storpoolVolumeDelete "$MEM_VOL" "force"
+        if [ $RET -eq 0 ]; then
+            echo "$res"
+        fi
+        splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID suffix:$res ($RET)"
+        exit $RET
+    fi
 
     if boolTrue "VMSNAPSHOT_FSFREEZE"; then
         rCMD=$(cat <<EOF
@@ -105,10 +192,6 @@ EOF
         splog "VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN is frosen"
         sleep ${VMSNAPSHOT_SLEEP:-.3}
     fi
-    for volume in $vmVolumes; do
-        snap="${volume}-${res}"
-        list+=($volume $snap)
-    done
     storpoolRetry groupSnapshot "tag:$VM_TAG=$VM_ID" ${list[@]}
     if boolTrue "VMSNAPSHOT_FSFREEZE"; then
         pids="$(jobs -p)"
diff --git a/vmm/kvm/snapshot_revert-storpool b/vmm/kvm/snapshot_revert-storpool
--- a/vmm/kvm/snapshot_revert-storpool
+++ b/vmm/kvm/snapshot_revert-storpool
@@ -55,6 +55,12 @@ if boolTrue "VMSNAPSHOT_OVERRIDE"; then
     for disk in $vmDisksMap; do
         vmVolumesMap["${disk%:*}"]="${disk##*:}"
     done
+
+    if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
+        MEM_VOL="${ONE_PX}-sys-${VM_ID}"
+        diskVolumes["$MEM_VOL"]="$MEM_VOL"
+    fi
+
     rCMD=$(cat <<EOF
     [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
 	while read -u 4 out; do
@@ -66,14 +72,18 @@ EOF
     $SSH "$VMHOST" "$rCMD" 2>/dev/null >/dev/null
     splog "VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN destroyed"
     sleep .5
-
     SP_TMP="SPTMP-$(date +%s)-$(mktemp --dry-run XXXXXXXX)"
     declare -a tmpVolumes snapList
+    MEM_VOL="${ONE_PX}-sys-${VM_ID}"
     while read -u 5 snap vid; do
         if boolTrue "DDEBUG_VMSNAPSHOT"; then
             splog "$snap vid:$vid"
         fi
         snapVol="${snap%-ONESNAP*}"
+        if [ "$snapVol" = "$MEM_VOL" ]; then
+            MEM_SNAP="$snap"
+            continue
+        fi
         if [ -n "$vid" ]; then
             if [ "$VM_ID" != "$vid" ]; then
                 if boolTrue "DEBUG_VMSNAPSHOT"; then
@@ -83,13 +93,19 @@ EOF
             fi
         elif [ -z "${diskVolumes["$snapVol"]}" ]; then
             if boolTrue "DEBUG_VMSNAPSHOT"; then
-                splog "Skip $snap (not in vmVolumes:$vmVolumes)"
+                splog "Skip $snap (not in diskVolumes:$diskVolumes)"
             fi
             continue
         fi
         snapList+=("$snap")
     done 5< <(storpoolRetry -j snapshot list |\
                   jq -r --arg snp "$SNAP_ID" --arg tag "$VM_TAG" '.data|map(select(.name|contains($snp)))[]|.name+" "+.tags[$tag]')
+    if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
+        if [ -z "$MEM_SNAP" ]; then
+           splog "Error: VMSNAPSHOT_WITH_CHECKPOINT is set but checkpoint snapshot not found"
+           exit 1
+        fi
+    fi
     splog "snapList: ${snapList[@]}"
     finish=1
     for snap in ${snapList[@]}; do
@@ -134,6 +150,55 @@ EOF
         for volume in ${tmpVolumes[@]}; do
             storpoolVolumeDelete "$volume" "force" "snaps"
         done
+    fi
+    if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
+        RET=$?
+        storpoolVolumeAttach "$MEM_SNAP" "$VMHOST" "ro" "snapshot"
+        MEM_LNK="/dev/storpool/$MEM_SNAP"
+        TDIR="$(mktemp -d)"
+        VM_XML="${TDIR}/restore-${VM_ID}.xml"
+        rCMD=$(cat <<EOF
+ mkdir "$TDIR"
+ RET=\$?
+ logger -t "${0##*/}_r[$$]" -- "mkdir $TDIR(\$RET)"
+ [ \$RET -eq 0 ] || exit \$RET
+ [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+ virsh --connect \$LIBVIRT_URI save-image-dumpxml "$MEM_LNK" >"$VM_XML"
+ RET=\$?
+ logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml $MEM_LNK >$VM_XML (\$RET)"
+ [ \$RET -eq 0 ] || exit \$RET
+ for i in 0 1 2; do
+   virsh --connect \$LIBVIRT_URI restore "$MEM_LNK" --xml $VM_XML &>>"$TDIR/restore-${VM_ID}-\${i}.log"
+   RET=\$?
+   logger -t "${0##*/}_r[$$]" -- "[\$i] virsh restore $MEM_LNK --xml $VM_XML (\$RET)"
+   if [ \$RET -ne 0 ]; then
+       logger -t "${0##*/}_r[$$]" -- "[\$i] Error: \$(cat "$TDIR/restore-${VM_ID}-\${i}.log")"
+   else
+       break
+   fi
+   sleep 0.5
+ done
+ rm -rf "$TDIR"
+ logger -t "${0##*/}_r[$$]" -- "END $VM_ID (\$RET)"
+ exit \$RET
+EOF
+)
+        splog "ssh $VMHOST virsh restore ..."
+        if $SSH "$VMHOST" "$rCMD" >"$TDIR/ssh.out" 2>"$TDIR/ssh.err"; then
+            splog "OK ssh $VMHOST ($?)"
+            RET=0
+        else
+            splog "ssh $VMHOST failed! ($?)"
+            splog "DEBUG_OUT:$(cat "$TDIR/ssh.out")"
+            splog "DEBUG_ERR:$(cat "$TDIR/ssh.err")"
+            RET=1
+        fi
+        storpoolVolumeDetach "$MEM_SNAP" "" "$VMHOST"
+        if [ $RET -ne 0 ]; then
+            splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID Failed! ($RET)"
+            exit $RET
+        fi
+        rm -rf "$TDIR"
     fi
     splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID"
     exit 0
