linting
Change-Id: I380a49fbc378211e1a2f14b6662fcbcccaa8b451

diff --git a/datastore/storpool/stat b/datastore/storpool/stat
--- a/datastore/storpool/stat
+++ b/datastore/storpool/stat
@@ -26,26 +26,29 @@
 # Set up the environment to source common tools
 #-------------------------------------------------------------------------------
 
-if [ -n "${ONE_LOCATION}" ]; then
-    LIB_LOCATION=$ONE_LOCATION/lib
+if [[ -n "${ONE_LOCATION}" ]]; then
+    LIB_LOCATION="${ONE_LOCATION}/lib"
 else
-    LIB_LOCATION=/usr/lib/one
+    LIB_LOCATION="/usr/lib/one"
 fi
 
-. $LIB_LOCATION/sh/scripts_common.sh
+# shellcheck source=/dev/null
+. "${LIB_LOCATION}/sh/scripts_common.sh"
 
-DRIVER_PATH=$(dirname $0)
-source ${DRIVER_PATH}/../libfs.sh
+DRIVER_PATH="$(dirname "$0")"
+# shellcheck source=/dev/null
+source "${DRIVER_PATH}/../libfs.sh"
 
-LOG_PREFIX="ds"
+export LOG_PREFIX="ds"
 
-source ${DRIVER_PATH}/../../tm/storpool/storpool_common.sh
+# shellcheck source=tm/storpool/storpool_common.sh
+source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"
 
 #-------------------------------------------------------------------------------
 # Get stat and datastore arguments from OpenNebula core
 #-------------------------------------------------------------------------------
 
-if [ -n "$2" ]; then
+if [[ -n "$2" ]]; then
     DRV_ACTION="$1"
     ID="$2"
 else
@@ -53,52 +56,52 @@ else
     ID="$1"
 fi
 
-oneDsDriverAction "$DRIVER_PATH"
+oneDsDriverAction "${DRIVER_PATH}"
 
 SIZE=0
 
 #-------------------------------------------------------------------------------
-# Test file 
+# Test file
 #-------------------------------------------------------------------------------
-[ -r "$IMAGE_PATH" ] || splog "Not readable file: $IMAGE_PATH"
-[ -w "$IMAGE_PATH" ] || splog "Not writable file: $IMAGE_PATH"
-[ -s "$IMAGE_PATH" ] || splog "Zero size file: $IMAGE_PATH"
+[[ -r "${IMAGE_PATH}" ]] || splog "Not readable file: ${IMAGE_PATH}"
+[[ -w "${IMAGE_PATH}" ]] || splog "Not writable file: ${IMAGE_PATH}"
+[[ -s "${IMAGE_PATH}" ]] || splog "Zero size file: ${IMAGE_PATH}"
 
 #-------------------------------------------------------------------------------
-# Compute the size 
+# Compute the size
 #-------------------------------------------------------------------------------
 
 case "${IMAGE_PATH,,}" in
     *vmdk|*vhdx)
-        SIZE=$($QEMU_IMG info "${IMAGE_PATH}" | sed -n 's/.*(\([0-9]*\) bytes).*/\1/p')
-        if [ $? -ne 0 ]; then
+        if ! SIZE=$(${QEMU_IMG:-qemu-img} info "${IMAGE_PATH}" | sed -n 's/.*(\([0-9]*\) bytes).*/\1/p' || true); then
             SIZE=0
         else
-            SIZE=$(echo $SIZE | tr -d "\r")
-            SIZE=$((($SIZE+1048575)/1048576))
+            SIZE=$(echo "${SIZE}" | tr -d "\r")
+            SIZE=$(((SIZE+1048575)/1048576))
         fi
         ;;
     *)
-        SIZE=`fs_size $IMAGE_PATH`
-        [ $? -eq 0 ] || SIZE=0
+        if ! SIZE=$(fs_size "${IMAGE_PATH}" || true); then
+            SIZE=0
+        fi
         ;;
 esac
 
-if [ "$SIZE" = "0" ]; then
+if [[ "${SIZE}" == "0" ]]; then
     oneSnapshotLookup "${IMAGE_PATH##*/}"
-    if [ -n "$SNAPSHOT_NAME" ]; then
-        storpoolSnapshotInfo "$SNAPSHOT_NAME"
+    if [[ -n "${SNAPSHOT_NAME}" ]]; then
+        storpoolSnapshotInfo "${SNAPSHOT_NAME}"
         SIZE="${SNAPSHOT_INFO[0]}"
         SIZE=$((SIZE/1024**2))
-        splog "$SNAPSHOT_NAME SIZE:$SIZE"
+        splog "${SNAPSHOT_NAME} SIZE:${SIZE}"
     fi
 fi
 
-if [ "$SIZE" = "0" ]; then
-    log_error "Cannot determine size for $IMAGE_PATH"
-    splog "Cannot determine size for $IMAGE_PATH"
-    exit -1
+if [[ "${SIZE}" == "0" ]]; then
+    log_error "Cannot determine size for ${IMAGE_PATH}"
+    splog "Cannot determine size for ${IMAGE_PATH}"
+    exit 255
 fi
 
-splog "END:$SIZE"
-echo "$SIZE"
+splog "END:${SIZE}"
+echo "${SIZE}"
diff --git a/tm/storpool/context b/tm/storpool/context
--- a/tm/storpool/context
+++ b/tm/storpool/context
@@ -37,36 +37,37 @@ VM_ID="${ARGV[$(($#-2))]}"
 DST="${ARGV[$(($#-3))]}"
 SRC=("${ARGV[@]:0:$(($#-3))}")
 
-TM_PATH="$(dirname $0)"
+TM_PATH="$(dirname "$0")"
+# shellcheck source=tm/storpool/storpool_common.sh
 source "${TM_PATH}/storpool_common.sh"
 
-splog "DS_ID=$DS_ID VM_ID=$VM_ID DST=$DST SRC=$SRC"
+splog "DS_ID=${DS_ID} VM_ID=${VM_ID} DST=${DST} SRC=${SRC[*]}"
 
-function exit_error
+function exit_error()
 {
-    error_message "$ERROR"
-    splog "$ERROR"
-    [ -d "$ISO_DIR" ] && rm -rf "$ISO_DIR" > /dev/null 2>&1
-    exit -1
+    error_message "${ERROR}"
+    splog "${ERROR}"
+    [[ -d "${ISO_DIR}" ]] && rm -rf "${ISO_DIR}" > /dev/null 2>&1
+    exit 255
 }
 
 #-------------------------------------------------------------------------------
 # Get Datastore information
 #-------------------------------------------------------------------------------
 
-oneDatastoreInfo "$DS_ID"
+oneDatastoreInfo "${DS_ID}"
 
 if boolTrue "AUTO_TEMPLATE"; then
-    if [ "$SP_PLACEALL" = "" ]; then
-        error_message "The template of the datastore with ID $DS_ID is missing 'SP_PLACEALL' attribute."
-        exit -1
+    if [[ -z "${SP_PLACEALL}" ]]; then
+        error_message "The template of the datastore with ID ${DS_ID} is missing 'SP_PLACEALL' attribute."
+        exit 255
     fi
-    if [ "$SP_PLACETAIL" = "" ]; then
-        SP_PLACETAIL="$SP_PLACEALL"
+    if [[ -z "${SP_PLACETAIL}" ]]; then
+        SP_PLACETAIL="${SP_PLACEALL}"
     fi
-    if [ -n "${SP_REPLICATION/[123]/}" ] || [ -n "${SP_REPLICATION/[[:digit:]]/}" ]; then
-        error_message "The template of the datastore with ID $DS_ID is with unknown value for 'SP_REPLICATION' attribute (SP_REPLICATION=$SP_REPLICATION)."
-        exit -1
+    if [[ -n "${SP_REPLICATION/[123]/}" || -n "${SP_REPLICATION/[[:digit:]]/}" ]]; then
+        error_message "The template of the datastore with ID ${DS_ID} is with unknown value for 'SP_REPLICATION' attribute (SP_REPLICATION=${SP_REPLICATION})."
+        exit 255
     fi
 fi
 
@@ -74,11 +75,11 @@ fi
 # Set dst path and dirs
 #-------------------------------------------------------------------------------
 
-DST_PATH=`arg_path $DST`
-DST_HOST=`arg_host $DST`
-DST_DIR=`dirname $DST_PATH`
+DST_PATH="$(arg_path "${DST}")"
+DST_HOST="$(arg_host "${DST}")"
+DST_DIR="$(dirname "${DST_PATH}")"
 
-DISK_ID=$(echo $DST | awk -F. '{print $NF}')
+DISK_ID="$(echo "${DST}" | awk -F. '{print $NF}')"
 
 #-------------------------------------------------------------------------------
 # Build the Context Block device (locally) and copy it remotely
@@ -86,83 +87,83 @@ DISK_ID=$(echo $DST | awk -F. '{print $NF}')
 
 log "Generating context block device"
 
-ISO_DIR="$DS_DIR/.isofiles/$VM_ID"
-ISO_FILE="$ISO_DIR/$VM_ID.iso"
+ISO_DIR="${DST_DIR}/.isofiles/${VM_ID}"
+ISO_FILE="${ISO_DIR}/${VM_ID}.iso"
 
-exec_and_set_error "mkdir -p $ISO_DIR" \
+exec_and_set_error "mkdir -p ${ISO_DIR}" \
     "Could not create tmp dir to make context dev"
-[ -n "$ERROR" ] && exit_error
+[[ -n "${ERROR}" ]] && exit_error
 
 for f in "${SRC[@]}"; do
-    case "$f" in
+    case "${f}" in
     http://*)
-        exec_and_set_error "$WGET -P '$ISO_DIR' $f" "Error downloading $f"
+        exec_and_set_error "${WGET:-wget} -P '${ISO_DIR}' ${f}" "Error downloading ${f}"
         ;;
     *)
-        if echo "$f" | grep -q ':'; then
-            target=$(echo "$f"|cut -d':' -f2-)
-            target="'$target'"
-            f=$(echo "$f"|cut -d':' -f1)
+        if echo "${f}" | grep -q ':'; then
+            target="$(echo "${f}" | cut -d':' -f2-)"
+            target="'${target}'"
+            f="$(echo "${f}" | cut -d':' -f1)"
         else
             target=""
         fi
 
-        exec_and_set_error "cp -R $f $ISO_DIR/$target" \
-            "Error copying $f to $ISO_DIR"
+        exec_and_set_error "cp -R ${f} ${ISO_DIR}/${target}" \
+            "Error copying ${f} to ${ISO_DIR}"
         ;;
     esac
 
-    [ -n "$ERROR" ] && exit_error
+    [[ -n "${ERROR}" ]] && exit_error
 done
 
-oneVmInfo "$VM_ID" 0
+oneVmInfo "${VM_ID}" 0
 
 SP_QOSCLASS="${VM_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}"
 debug_sp_qosclass
 
 if boolTrue "INCLUDE_CONTEXT_PACKAGES"; then
-    if [ -d /usr/share/one/context ]; then
+    if [[ -d "/usr/share/one/context" ]]; then
         exec_and_set_error "rsync -a --exclude='*.iso' /usr/share/one/context/* '${ISO_DIR}'/" \
             "Error copying /usr/share/one/context to ${ISO_DIR}"
     fi
 fi
 
-exec_and_set_error "$MKISOFS -o $ISO_FILE -V CONTEXT -J -R $ISO_DIR" \
+exec_and_set_error "${MKISOFS:-mkisofs} -o ${ISO_FILE} -V CONTEXT -J -R ${ISO_DIR}" \
     "Error creating iso fs"
-[ -n "$ERROR" ] && exit_error
+[[ -n "${ERROR}" ]] && exit_error
 
-SP_SIZE=$(du -b "$ISO_FILE" | cut -f1)
-SP_SIZE=$(( (SP_SIZE +511) /512 *512 ))
+SP_SIZE="$(du -b "${ISO_FILE}" | cut -f1 || true)"
+SP_SIZE="$(( (SP_SIZE +511) /512 *512 ))"
 SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}-iso"
-SP_LINK="/dev/storpool/$SP_VOL"
-SP_TEMPLATE="${ONE_PX}-ds-$DS_ID"
+SP_LINK="/dev/storpool/${SP_VOL}"
+SP_TEMPLATE="${ONE_PX}-ds-${DS_ID}"
 
-if storpoolVolumeExists "$SP_VOL"; then
-    storpoolVolumeResize "$SP_VOL" "$SP_SIZE" "shrinkOk"
-    storpoolTemplate "$SP_TEMPLATE"
+if storpoolVolumeExists "${SP_VOL}"; then
+    storpoolVolumeResize "${SP_VOL}" "${SP_SIZE}" "shrinkOk"
+    storpoolTemplate "${SP_TEMPLATE}"
 else
-    storpoolVolumeCreate "$SP_VOL" "$SP_SIZE" "$SP_TEMPLATE"
+    storpoolVolumeCreate "${SP_VOL}" "${SP_SIZE}" "${SP_TEMPLATE}"
 fi
 
 #-------------------------------------------------------------------------------
 # Import image to the context volume
 #-------------------------------------------------------------------------------
 
-storpoolVolumeAttach "$SP_VOL" "$DST_HOST"
-PIPE_CMD="cat $ISO_FILE"
-splog "eval $PIPE_CMD | $SSH $DST_HOST $DD of=/dev/storpool/$SP_VOL bs=512k conv=fdatasync status=none iflag=fullblock oflag=direct"
-exec_and_log "eval $PIPE_CMD | $SSH $DST_HOST $DD of=/dev/storpool/$SP_VOL bs=512k conv=fdatasync status=none iflag=fullblock oflag=direct" \
-            "Error importing $ISO_FILE to $DST_HOST:/dev/storpool/$SP_VOL"
+storpoolVolumeAttach "${SP_VOL}" "${DST_HOST}"
+PIPE_CMD="cat ${ISO_FILE}"
+splog "eval ${PIPE_CMD} | ${SSH:-ssh} ${DST_HOST} ${DD:-dd} of=/dev/storpool/${SP_VOL} bs=512k conv=fdatasync status=none iflag=fullblock oflag=direct"
+exec_and_log "eval ${PIPE_CMD} | ${SSH:-ssh} ${DST_HOST} ${DD:-dd} of=/dev/storpool/${SP_VOL} bs=512k conv=fdatasync status=none iflag=fullblock oflag=direct" \
+            "Error importing ${ISO_FILE} to ${DST_HOST}:/dev/storpool/${SP_VOL}"
 
 #-------------------------------------------------------------------------------
 # (re)attach readonly
 #------------------------------------------------------------------------------
 if [[ "${READONLY_MODE}" == "ro" ]]; then
-    storpoolVolumeAttach "$SP_VOL" "$DST_HOST" "ro"
+    storpoolVolumeAttach "${SP_VOL}" "${DST_HOST}" "ro"
 fi
 
 if boolTrue "TAG_CONTEXT_ISO"; then
-    storpoolVolumeTag "$SP_VOL" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG};$VM_TAG;${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}"
+    storpoolVolumeTag "${SP_VOL}" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}"
 fi
 
 MONITOR_TM_MAD=
@@ -170,54 +171,54 @@ if ! boolTrue "DS_SHARED"; then
     MONITOR_TM_MAD="storpool"
 fi
 
-oneSymlink "$DST_HOST" "$SP_LINK" "$DST_PATH"
+oneSymlink "${DST_HOST}" "${SP_LINK}" "${DST_PATH}"
 
 #-------------------------------------------------------------------------------
 # Remove ISO file and source dir
 #-------------------------------------------------------------------------------
 
-rm -rf "$ISO_FILE" > /dev/null 2>&1
-rm -rf "$ISO_DIR" > /dev/null 2>&1
+rm -rf "${ISO_FILE}" > /dev/null 2>&1
+rm -rf "${ISO_DIR}" > /dev/null 2>&1
 
 if boolTrue "FORCE_DETACH_OTHER_CONTEXT"; then
-    forceDetachOther "$VM_ID" "$DST_HOST"
+    forceDetachOther "${VM_ID}" "${DST_HOST}"
 fi
 
-if [ -n "$T_OS_NVRAM" ]; then
-    t_os_nvram=(${T_OS_NVRAM#*:})
+if [[ -n "${T_OS_NVRAM:-}" ]]; then
+    read -r -a t_os_nvram <<< "${T_OS_NVRAM#*:}"
     NVRAM_TEMPLATE="${t_os_nvram[0]#*=}"
-    t_arr=(${NVRAM_TEMPLATE//\// })
-    if [ "${NVRAM_TEMPLATE#*/}" = "$NVRAM_TEMPLATE" ]; then
+    # read -r -a t_arr <<< "${NVRAM_TEMPLATE//\// }"  # TBD: remove
+    if [[ "${NVRAM_TEMPLATE#*/}" == "${NVRAM_TEMPLATE}" ]]; then
         NVRAM_TEMPLATE="${OVMF_PATH:-/var/lib/one/remotes/OVMF}/${NVRAM_TEMPLATE}"
     fi
-    if [ -f "$NVRAM_TEMPLATE" ]; then
+    if [[ -f "${NVRAM_TEMPLATE:-}" ]]; then
         SP_VOL="${ONE_PX}-sys-${VM_ID}-NVRAM"
-        SP_LINK="/dev/storpool/$SP_VOL"
-        if ! storpoolVolumeExists "$SP_VOL"; then
-            SIZE=$(stat --printf=%s "$NVRAM_TEMPLATE")
-            if [ -n "$SIZE" ]; then
-                splog "NVRAM_TEMPLATE=$NVRAM_TEMPLATE SIZE=$SIZE //$T_OS_NVRAM"
-                storpoolVolumeCreate "$SP_VOL" "$SIZE" "$SP_TEMPLATE"
-                trapAdd "storpoolVolumeDelete \"$SP_VOL\""
-                storpoolVolumeAttach "$SP_VOL" "$DST_HOST"
-                trapAdd "storpoolVolumeDetach \"$SP_VOL\" \"force\" \"\" \"all\""
-                PIPE_CMD="$DD if=\"$NVRAM_TEMPLATE\" bs=128k status=none conv=fdatasync"
-                splog "eval $PIPE_CMD | $SSH $DST_HOST $DD of=$SP_LINK bs=128k conv=fdatasync status=none iflag=fullblock oflag=direct"
-                exec_and_log "eval $PIPE_CMD | $SSH $DST_HOST $DD of=$SP_LINK bs=128k conv=fdatasync status=none iflag=fullblock oflag=direct" \
-                    "Error importing $NVRAM_TEMPLATE to ${DST_HOST}:${SP_LINK}"
+        SP_LINK="/dev/storpool/${SP_VOL}"
+        if ! storpoolVolumeExists "${SP_VOL}"; then
+            SIZE=$(stat --printf=%s "${NVRAM_TEMPLATE:-}")
+            if [[ -n "${SIZE:-}" ]]; then
+                splog "NVRAM_TEMPLATE=${NVRAM_TEMPLATE:-} SIZE=${SIZE:-} // ${T_OS_NVRAM:-}"
+                storpoolVolumeCreate "${SP_VOL}" "${SIZE}" "${SP_TEMPLATE}"
+                trapAdd "storpoolVolumeDelete \"${SP_VOL}\""
+                storpoolVolumeAttach "${SP_VOL}" "${DST_HOST}"
+                trapAdd "storpoolVolumeDetach \"${SP_VOL}\" \"force\" \"\" \"all\""
+                PIPE_CMD="${DD:-dd} if=\"${NVRAM_TEMPLATE}\" bs=128k status=none conv=fdatasync"
+                splog "eval ${PIPE_CMD} | ${SSH:-ssh} ${DST_HOST} ${DD:-dd} of=${SP_LINK} bs=128k conv=fdatasync status=none iflag=fullblock oflag=direct"
+                exec_and_log "eval ${PIPE_CMD} | ${SSH:-ssh} ${DST_HOST} ${DD:-dd} of=${SP_LINK} bs=128k conv=fdatasync status=none iflag=fullblock oflag=direct" \
+                    "Error importing ${NVRAM_TEMPLATE:-} to ${DST_HOST}:${SP_LINK}"
                 trapReset
-                storpoolVolumeTag "$SP_VOL" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG};$VM_TAG;${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}"
+                storpoolVolumeTag "${SP_VOL}" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}"
 
             else
-                splog "Can't get the size of $NVRAM_TEMPLATE!"
+                splog "Can't get the size of ${NVRAM_TEMPLATE:-}!"
             fi
         else
-            storpoolVolumeAttach "$SP_VOL" "$DST_HOST"
+            storpoolVolumeAttach "${SP_VOL}" "${DST_HOST}"
         fi
     else
-        splog "NVRAM_TEMPLATE='$NVRAM_TEMPLATE' not found!"
+        splog "NVRAM_TEMPLATE='${NVRAM_TEMPLATE:-}' not found!"
     fi
 fi
 
-splog "END $VM_ID"
+splog "END ${VM_ID}"
 exit 0
diff --git a/vmm/kvm/snapshot_create-storpool b/vmm/kvm/snapshot_create-storpool
--- a/vmm/kvm/snapshot_create-storpool
+++ b/vmm/kvm/snapshot_create-storpool
@@ -31,188 +31,198 @@ SNAP_ID="$2"
 VM_ID="$3"
 VMHOST="$4"
 
-DRIVER_PATH="$(dirname $0)"
+DRIVER_PATH="$(dirname "$0")"
 VMSNAPSHOT_TAG="ONESNAP"
 VMSNAPSHOT_OVERRIDE=1
 
-[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ] && source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" || source "${DRIVER_PATH}/kvmrc"
+if [[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
+    # shellcheck source=/dev/null
+    source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc"
+else
+    # shellcheck source=/dev/null
+    source "${DRIVER_PATH}/kvmrc"
+fi
+# shellcheck source=/dev/null
 source "${DRIVER_PATH}/../../scripts_common.sh"
+# shellcheck source=tm/storpool/storpool_common.sh
 source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"
 
-LOG_PREFIX="vmm"
+export LOG_PREFIX="vmm"
 
 splog "$0 $*"
 
 if boolTrue "VMSNAPSHOT_OVERRIDE"; then
-    oneVmVolumes "$VM_ID"
-    oneDatastoreInfo "$VM_DS_ID"
+    oneVmVolumes "${VM_ID}"
+    oneDatastoreInfo "${VM_DS_ID}"
 
-    splog "vmDisks:$vmDisks vmVolumes:'$vmVolumes'"
-    if [ -n "$oneVmVolumesShareable" ]; then
-        res="VM Snapshot of shareable disk is not supported!($oneVmVolumesShareable)"
-        error_message "$res"
-        splog "$res (exit 1)"
+    splog "vmDisks:${vmDisks} vmVolumes:${vmVolumes}"
+    if [[ -n "${oneVmVolumesShareable}" ]]; then
+        res="VM Snapshot of shareable disk is not supported!(${oneVmVolumesShareable})"
+        error_message "${res}"
+        splog "${res} (exit 1)"
         exit 1
     fi
     if boolTrue "VMSNAPSHOT_ENABLE_LIMIT"; then
-        if [ -n "$VM_VMSNAPSHOT_LIMIT" ]; then
-            VMSNAPSHOT_LIMIT="$VM_VMSNAPSHOT_LIMIT"
+        if [[ -n "${VM_VMSNAPSHOT_LIMIT}" ]]; then
+            VMSNAPSHOT_LIMIT="${VM_VMSNAPSHOT_LIMIT}"
         fi
-        if [ -n "$VMSNAPSHOT_LIMIT" ]; then
-            if [ "${VMSNAPSHOT_LIMIT//[[:digit:]]}" = "" ]; then
-                if [ $VMSNAPSHOT_LIMIT -lt ${#SNAPSHOT_ID_A[@]} ]; then
-                    res="VMSNAPSHOT_LIMIT of $VMSNAPSHOT_LIMIT snaphosts exceeded!"
-                    splog "$res"
-                    error_message "$res"
+        if [[ -n "${VMSNAPSHOT_LIMIT}" ]]; then
+            if [[ -z "${VMSNAPSHOT_LIMIT//[[:digit:]]}" ]]; then
+                if [[ "${VMSNAPSHOT_LIMIT}" -lt "${#SNAPSHOT_ID_A[@]}" ]]; then
+                    res="VMSNAPSHOT_LIMIT of ${VMSNAPSHOT_LIMIT} snaphosts exceeded!"
+                    splog "${res}"
+                    error_message "${res}"
                     exit 1
                 else
-                    res="VM snapshots limit VMSNAPSHOT_LIMIT:$VMSNAPSHOT_LIMIT >= ${#SNAPSHOT_ID_A[@]}"
-                    splog "$res"
-                    log "$res"
+                    res="VM snapshots limit VMSNAPSHOT_LIMIT:${VMSNAPSHOT_LIMIT} >= ${#SNAPSHOT_ID_A[@]}"
+                    splog "${res}"
+                    log "${res}"
                 fi
             else
-                res="Error: VMSNAPSHOT_LIMIT='$VMSNAPSHOT_LIMIT' Not a number"
-                splog "$res"
-                error_message "$res"
+                res="Error: VMSNAPSHOT_LIMIT='${VMSNAPSHOT_LIMIT}' Not a number"
+                splog "${res}"
+                error_message "${res}"
                 exit 1
             fi
         fi
     fi
     ts=$(date +%s)
     res="${VMSNAPSHOT_TAG}-${SNAP_ID}-${ts}"
-    for volume in $vmVolumes; do
+    for volume in ${vmVolumes}; do
         snap="${volume}-${res}"
-        list+=($volume $snap)
+        list+=("${volume}" "${snap}")
     done
     if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
         # get guest memory
         rCMD=$(cat <<EOF
-    [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
-    virsh --connect \$LIBVIRT_URI dumpxml "$DOMAIN"
+    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+    virsh --connect \${LIBVIRT_URI:-qemu:///system} dumpxml "${DOMAIN}"
 EOF
 )
-        domXML="$($SSH "$VMHOST" "$rCMD")"
-        domMem=$(echo "$domXML" | xmlstarlet sel -t -v domain/memory)
+        domXML="$(${SSH:-ssh} "${VMHOST}" "${rCMD}")"
+        domMem=$(echo "${domXML}" | xmlstarlet sel -t -v domain/memory)
         MEM_VOL="${ONE_PX}-sys-${VM_ID}"
-        storpoolVolumeCreate "$MEM_VOL" "$((domMem * 2))K" "${ONE_PX}-ds-${VM_DS_ID}"
+        storpoolVolumeCreate "${MEM_VOL}" "$((domMem * 2))K" "${ONE_PX}-ds-${VM_DS_ID}"
         RET=$?
-        if [ $RET -ne 0 ]; then
+        if [[ "${RET}" -ne 0 ]]; then
             splog "Can't create checkpoint volume! Domain memory ${domMem}K"
         fi
-        storpoolVolumeAttach "$MEM_VOL" "$VMHOST"
-        if [ $RET -ne 0 ]; then
-            splog "Can't attach checkpoint volume to $VMHOST!"
+        storpoolVolumeAttach "${MEM_VOL}" "${VMHOST}"
+        if [[ "${RET}" -ne 0 ]]; then
+            splog "Can't attach checkpoint volume to ${VMHOST}!"
         fi
-        list+=($MEM_VOL ${MEM_VOL}-$res)
-        json="$(volumesGroupSnapshotJson "tag:$VM_TAG=${VM_ID}" "tag:${LOC_TAG}=${LOC_TAG_VAL}" "tag:virt=one" ${list[@]})"
-        apiCmd="$(storpoolApiCmdline=1 storpoolApi "VolumesGroupSnapshot" "$json")"
-        MEM_LNK="/dev/storpool/$MEM_VOL"
+        list+=("${MEM_VOL}" "${MEM_VOL}-${res}")
+        json="$(volumesGroupSnapshotJson "tag:${VM_TAG:-nvm}=${VM_ID}" "tag:${LOC_TAG:-nloc}=${LOC_TAG_VAL}" "tag:virt=one" "${list[@]}")"
+        apiCmd="$(storpoolApiCmdline=1 storpoolApi "VolumesGroupSnapshot" "${json}")"
+        MEM_LNK="/dev/storpool/${MEM_VOL}"
         TDIR="$(mktemp -d)"
-        trapAdd "rm -rf $TDIR"
-        VM_XML="$TDIR/one-${VM_ID}.XML"
+        trapAdd "rm -rf ${TDIR}"
+        VM_XML="${TDIR}/one-${VM_ID}.XML"
         rCMD=$(cat <<EOF
- mkdir "$TDIR"
+ mkdir "${TDIR}"
  RET=\$?
- logger -t "${0##*/}_r[$$]" -- "mkdir $TDIR(\$RET)"
- [ \$RET -eq 0 ] || exit \$RET
- [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
- virsh --connect \$LIBVIRT_URI save "$DOMAIN" "$MEM_LNK"
+ logger -t "${0##*/}_r[$$]" -- "mkdir ${TDIR}(\${RET})"
+ [[ \${RET} -eq 0 ]] || exit "\${RET}"
+ [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+ virsh --connect \${LIBVIRT_URI:-qemu:///system} save "${DOMAIN}" "${MEM_LNK}"
  RET=\$?
- logger -t "${0##*/}_r[$$]" -- "virsh save "$DOMAIN" "$MEM_LNK" (\$RET)"
- [ \$RET -eq 0 ] || exit \$RET
- virsh --connect \$LIBVIRT_URI save-image-dumpxml "$MEM_LNK" >"$VM_XML"
+ logger -t "${0##*/}_r[$$]" -- "virsh save ${DOMAIN} ${MEM_LNK} (\$RET)"
+ [[ \${RET} -eq 0 ]] || exit "\${RET}"
+ virsh --connect \${LIBVIRT_URI:-qemu:///system} save-image-dumpxml "${MEM_LNK}" >"${VM_XML}"
  RET=\$?
- logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml $MEM_LNK >$VM_XML (\$RET)"
- [ \$RET -eq 0 ] || exit \$RET
- $apiCmd >"$TDIR/curl.out" 2>"$TDIR/curl.err"
+ logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml ${MEM_LNK} >${VM_XML} (\$RET)"
+ [[ \${RET} -eq 0 ]] || exit "\${RET}"
+ ${apiCmd} >"${TDIR}/curl.out" 2>"${TDIR}/curl.err"
  RET=\$?
  APIRET=42
- logger -t "${0##*/}_r[$$]" -- "volumeGroupSnapshot (\$RET) \$(cat "$TDIR/curl.out")"
- if [ \$RET -eq 0 ]; then
-   OK=\$(jq -r '.data.ok' "$TDIR/curl.out" 2>/dev/null)
-   if [ "\$OK" = "true" ]; then
+ logger -t "${0##*/}_r[$$]" -- "volumeGroupSnapshot (\${RET}) \$(cat "${TDIR}/curl.out")"
+ if [[ \${RET} -eq 0 ]]; then
+   OK=\$(jq -r '.data.ok' "${TDIR}/curl.out" 2>/dev/null)
+   if [[ "\${OK}" == "true" ]]; then
      APIRET=0
    else
-     logger -t "${0##*/}_r[$$]" -- "Error: OK='\$OK'"
+     logger -t "${0##*/}_r[$$]" -- "Error: OK='\${OK}'"
    fi
  else
-   logger -t "${0##*/}_r[$$]" -- "Curl error: \$(cat "$TDIR/curl.err")"
-   exit \$RET
+   logger -t "${0##*/}_r[$$]" -- "Curl error: \$(cat "${TDIR}/curl.err")"
+   exit "\${RET}"
  fi
  for i in 0 1 2; do
-   virsh --connect \$LIBVIRT_URI restore "$MEM_LNK" --xml $VM_XML &>>/tmp/one-${VM_ID}-\$i.log
+   virsh --connect \${LIBVIRT_URI:-qemu:///system} restore "${MEM_LNK}" --xml "${VM_XML}" &>>/tmp/one-${VM_ID}-\${i}.log
    RET=\$?
-   logger -t "${0##*/}_r[$$]" -- "[\$i] virsh restore $MEM_LNK --xml $VM_XML (\$RET)"
-   [ \$RET -ne 0 ] || break
+   logger -t "${0##*/}_r[$$]" -- "[\${i}] virsh restore ${MEM_LNK} --xml ${VM_XML} (\${RET})"
+   [[ \${RET} -ne 0 ]] || break
    sleep 0.5
  done
- logger -t "${0##*/}_r[$$]" -- "END $VM_ID (\$APIRET::\$RET)"
- rm -rf "$TDIR"
- exit \$((RET + APIRET))
+ logger -t "${0##*/}_r[$$]" -- "END ${VM_ID} (\${APIRET}::\${RET})"
+ rm -rf "${TDIR}"
+ exit "\$((RET + APIRET))"
 EOF
 )
-        if $SSH "$VMHOST" "$rCMD" >"$TDIR/ssh.out" 2>"$TDIR/ssh.err"; then
-            splog "OK ssh $VMHOST ($?)"
+        if ${SSH:-ssh} "${VMHOST}" "${rCMD}" >"${TDIR}/ssh.out" 2>"${TDIR}/ssh.err"; then
+            splog "OK ssh ${VMHOST} ($?)"
             RET=0
         else
-            splog "ssh $VMHOST failed! ($?)"
-            splog "DEBUG_OUT:$(cat "$TDIR/ssh.out")"
-            splog "DEBUG_ERR:$(cat "$TDIR/ssh.err")"
+            splog "ssh ${VMHOST} failed! ($?)"
+            splog "DEBUG_OUT:$(cat "${TDIR}/ssh.out"||true)"
+            splog "DEBUG_ERR:$(cat "${TDIR}/ssh.err"||true)"
             RET=1
         fi
-        storpoolVolumeDelete "$MEM_VOL" "force"
-        if [ $RET -eq 0 ]; then
-            echo "$res"
+        storpoolVolumeDelete "${MEM_VOL}" "force"
+        if [[ "${RET}" -eq 0 ]]; then
+            echo "${res}"
         fi
-        splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID suffix:$res ($RET)"
-        exit $RET
+        splog "END VM_ID=${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID} suffix:${res} (${RET})"
+        exit "${RET}"
     fi
 
     if boolTrue "VMSNAPSHOT_FSFREEZE"; then
         rCMD=$(cat <<EOF
-    PARENTPID=\$PPID
-    #echo "$DOMAIN"
-    [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
-    trap 'virsh --connect '\$LIBVIRT_URI' qemu-agent-command "'$DOMAIN'" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null ;\
-    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw '$DOMAIN' ret:\$? \$(date +%s.%N) trap"' EXIT QUIT TERM INT HUP
-    virsh --connect \$LIBVIRT_URI qemu-agent-command "$DOMAIN" "{\"execute\":\"guest-fsfreeze-freeze\"}" 2>&1 >/dev/null
-    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsfreeze $DOMAIN ret:\$? \$(date +%s.%N)"
+    PARENTPID=\${PPID}
+    #echo "${DOMAIN}"
+    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+    trap 'virsh --connect \${LIBVIRT_URI:-qemu:///system} qemu-agent-command "'${DOMAIN}'" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null ;\
+    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw '${DOMAIN}' ret:\$? \$(date +%s.%N) trap"' EXIT QUIT TERM INT HUP
+    virsh --connect \${LIBVIRT_URI:-qemu:///system} qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-freeze\"}" 2>&1 >/dev/null
+    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsfreeze ${DOMAIN} ret:\$? \$(date +%s.%N)"
     while [ -d /proc/\$PARENTPID ]; do
-        logger -t "vmm_sp_snapshot_create_r[\$\$]" "$DOMAIN \$(virsh --connect \$LIBVIRT_URI qemu-agent-command "$DOMAIN" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)"
+        logger -t "vmm_sp_snapshot_create_r[\$\$]" "${DOMAIN} \$(virsh --connect \${LIBVIRT_URI:-qemu:///system} qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)"
         sleep ${VMSNAPSHOT_SLEEP_REMOTE:-.1}
     done
-    virsh --connect \$LIBVIRT_URI qemu-agent-command "$DOMAIN" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null
-    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw $DOMAIN ret:\$? \$(date +%s.%N)"
-    logger -t "vmm_sp_snapshot_create_r[\$\$]" \$(virsh --connect \$LIBVIRT_URI qemu-agent-command "$DOMAIN" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)
+    virsh --connect \${LIBVIRT_URI:-qemu:///system} qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null
+    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw ${DOMAIN} ret:\$? \$(date +%s.%N)"
+    logger -t "vmm_sp_snapshot_create_r[\$\$]" \$(virsh --connect \${LIBVIRT_URI:-qemu:///system} qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)
     #trap - TERM INT QUIT HUP
 EOF
 )
+        # shellcheck disable=SC2064
         trap "trap - SIGTERM && kill -- -$$" TERM INT QUIT HUP EXIT
-        $SSH "$VMHOST" "$rCMD" 2>/dev/null >/dev/null &
-        splog "VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN is frosen"
-        sleep ${VMSNAPSHOT_SLEEP:-.3}
+        ${SSH:-ssh} "${VMHOST}" "${rCMD}" 2>/dev/null >/dev/null &
+        splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} is frosen"
+        sleep "${VMSNAPSHOT_SLEEP:-.3}"
     fi
-    storpoolRetry groupSnapshot "tag:$VM_TAG=${VM_ID}" "tag:$LOC_TAG=${LOC_TAG_VAL}" "tag:virt=one" ${list[@]}
+    storpoolRetry groupSnapshot "tag:${VM_TAG:-nvm}=${VM_ID}" "tag:${LOC_TAG:-nloc}=${LOC_TAG_VAL}" "tag:virt=one" "${list[@]}"
     if boolTrue "VMSNAPSHOT_FSFREEZE"; then
         pids="$(jobs -p)"
-        if [ -n "$pids" ]; then
-            kill $pids 2>/dev/null >/dev/null
+        if [[ -n "${pids}" ]]; then
+            # shellcheck disable=SC2086
+            kill ${pids} 2>/dev/null >/dev/null
             ret=$?
-            splog "kill $pids ($ret)"
-            if [ $ret -eq 0 ]; then
-                splog "VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN is thawed"
+            splog "kill ${pids} (${ret})"
+            if [[ "${ret}" -eq 0 ]]; then
+                splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} is thawed"
                 trap - TERM INT QUIT HUP EXIT
             else
-                splog "Unable to kill the process holding the VM with freezed filesystem VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN"
+                splog "Unable to kill the process holding the VM with freezed filesystem VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN}"
             fi
         fi
     fi
-    echo "$res"
-    splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID suffix:$res"
+    echo "${res}"
+    splog "END VM_ID=${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID} suffix:${res}"
     exit 0
 else
     res="VMSNAPSHOT_OVERRIDE is not set"
-    splog "$res"
-    error_message "$res"
+    splog "${res}"
+    error_message "${res}"
     exit 1
 fi
diff --git a/vmm/kvm/snapshot_revert-storpool b/vmm/kvm/snapshot_revert-storpool
--- a/vmm/kvm/snapshot_revert-storpool
+++ b/vmm/kvm/snapshot_revert-storpool
@@ -31,196 +31,205 @@ SNAP_ID="$2"
 VM_ID="$3"
 VMHOST="$4"
 
-DRIVER_PATH="$(dirname $0)"
+DRIVER_PATH="$(dirname "$0")"
 VMSNAPSHOT_TAG="ONESNAP"
 VMSNAPSHOT_OVERRIDE=1
 DS_PATH="/var/lib/one/datastores"
+export DS_PATH
 
-[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ] && source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" || source "${DRIVER_PATH}/kvmrc"
+if [[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
+    # shellcheck source=/dev/null
+    source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc"
+else
+    # shellcheck source=/dev/null
+    source "${DRIVER_PATH}/kvmrc"
+fi
+# shellcheck source=/dev/null
 source "${DRIVER_PATH}/../../scripts_common.sh"
+# shellcheck source=tm/storpool/storpool_common.sh
 source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"
 
-LOG_PREFIX="vmm"
+export LOG_PREFIX="vmm"
 
 if boolTrue "DEBUG_VMSNAPSHOT"; then
-    splog "$0 $*"
+    splog "[D] $0 $*"
 fi
 
 if boolTrue "VMSNAPSHOT_OVERRIDE"; then
-    oneVmVolumes "$VM_ID"
-    oneDatastoreInfo "$VM_DS_ID"
-    
+    oneVmVolumes "${VM_ID}"
+    oneDatastoreInfo "${VM_DS_ID}"
+
     declare -A vmVolumesMap diskVolumes vmVolumesQcMap
-    for v in $vmVolumes; do
-        diskVolumes["$v"]="$v"  # diskVolumes[VOLUME_NAME]=VOLUME_NAME
+    for volume in ${vmVolumes}; do
+        diskVolumes["${volume}"]="${volume}"  # diskVolumes[VOLUME_NAME]=VOLUME_NAME
     done
-    for disk in $vmDisksMap; do
+    for disk in ${vmDisksMap}; do
         vmVolumesMap["${disk%:*}"]="${disk##*:}"  # vmVolumesMap[DISK_ID]=VOLUME_NAME
     done
 
     if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
         MEM_VOL="${ONE_PX}-sys-${VM_ID}"
-        diskVolumes["$MEM_VOL"]="$MEM_VOL"
+        diskVolumes["${MEM_VOL}"]="${MEM_VOL}"
     fi
-    for v in $vmVolumesQc; do
-        vmVolumesQcMap["${v%%:*}"]="${v##*:}"  # vmVolumesQcMap[VOLUME_NAME]=QOSCLASS
+    for volume in ${vmVolumesQc:-}; do
+        vmVolumesQcMap["${volume%%:*}"]="${volume##*:}"  # vmVolumesQcMap[VOLUME_NAME]=QOSCLASS
     done
 
     rCMD=$(cat <<EOF
-    [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
-	while read -u 4 out; do
-        logger -t vmm_sp_snapshot_revert_r "virsh: \$out"
-    done 4< <(virsh --connect \$LIBVIRT_URI destroy "$DOMAIN" 2>&1)
-    logger -t vmm_sp_snapshot_revert_r "virsh destroy $DOMAIN ret:\$?"
+    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+	while read -r -u "\${virshfd}" out; do
+        logger -t vmm_sp_snapshot_revert_r "virsh: \${out}"
+    done {virshfd}< <(virsh --connect "${LIBVIRT_URI:-qemu:///system}" destroy "${DOMAIN}" 2>&1)
+    logger -t vmm_sp_snapshot_revert_r "virsh destroy ${DOMAIN} ret:\$?"
 EOF
 )
-    $SSH "$VMHOST" "$rCMD" 2>/dev/null >/dev/null
-    splog "VM $VM_ID host:$VMHOST DOMAIN_ID:$DOMAIN destroyed"
+    ${SSH:-ssh} "${VMHOST}" "${rCMD}" 2>/dev/null >/dev/null
+    splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} destroyed"
     sleep .5
-    SP_TMP="SPTMP-$(date +%s)-$(mktemp --dry-run XXXXXXXX)"
+    SP_TMP="SPTMP-$(date +%s||true)-$(mktemp --dry-run XXXXXXXX)"
     declare -a tmpVolumes snapList
     MEM_VOL="${ONE_PX}-sys-${VM_ID}"
-    while read -u 5 snap vmtag loctagval; do
+    while read -r -u "${spfd}" snap vmtag loctagval; do
         if boolTrue "DDEBUG_VMSNAPSHOT"; then
-            splog "$snap vmtag:$vmtag loctagval:$loctagval"
+            splog "[DD] ${snap} vmtag:${vmtag} loctagval:${loctagval}"
         fi
-        snapVol="${snap%-${VMSNAPSHOT_TAG}*}"
-        if [ "$snapVol" = "$MEM_VOL" ]; then
-            MEM_SNAP="$snap"
+        snapVol="${snap%"-${VMSNAPSHOT_TAG}"*}"
+        if [[ "${snapVol}" == "${MEM_VOL}" ]]; then
+            MEM_SNAP="${snap}"
             continue
         fi
-        if [ -n "${vmtag/null/}" ]; then
-            if [ "${VM_ID}" != "$vmtag" ]; then
+        if [[ -n "${vmtag/null/}" ]]; then
+            if [[ "${VM_ID}" != "${vmtag}" ]]; then
                 if boolTrue "DEBUG_VMSNAPSHOT"; then
-                    splog "Skip $snap (${VM_ID} != $vmtag, VM_TAG=$VM_TAG)"
+                    splog "[D] Skip ${snap} (${VM_ID} != ${vmtag}, VM_TAG=${VM_TAG})"
                 fi
                 continue
             fi
-            if [ -n "${loctagval/null/}" ]; then
-                if [ "$loctagval" != "$LOC_TAG_VAL" ]; then
+            if [[ -n "${loctagval/null/}" ]]; then
+                if [[ "${loctagval}" != "${LOC_TAG_VAL}" ]]; then
                     if boolTrue "DEBUG_VMSNAPSHOT"; then
-                        splog "Skip $snap (loctagval $loctagval != $LOC_TAG_VAL)"
+                        splog "[D] Skip ${snap} (loctagval ${loctagval} != ${LOC_TAG_VAL})"
                     fi
                     continue
                 fi
             fi
-        elif [ -z "${diskVolumes["$snapVol"]}" ]; then
+        elif [[ -z "${diskVolumes["${snapVol}"]}" ]]; then
             if boolTrue "DEBUG_VMSNAPSHOT"; then
-                splog "Skip $snap (not in diskVolumes:$diskVolumes)"
+                splog "[D] Skip ${snap} (not in diskVolumes:${!diskVolumes})"
             fi
             continue
         fi
-        snapList+=("$snap")
-    done 5< <(storpoolRetry -j snapshot list |\
-                  jq -r --arg snp "$SNAP_ID" --arg vmtag "$VM_TAG" --arg loctag "$LOC_TAG" \
-                      '.data|map(select(.name|contains($snp)))[]|.name+" "+.tags[$vmtag]+" "+.tags[$loctag]')
+        snapList+=("${snap}")
+    done {spfd}< <(storpoolRetry -j snapshot list |\
+                  jq -r --arg snp "${SNAP_ID}" --arg vmtag "${VM_TAG:-nvm}" --arg loctag "${LOC_TAG:-nloc}" \
+                      '.data|map(select(.name|contains($snp)))[]|.name+" "+.tags[$vmtag]+" "+.tags[$loctag]' || true)
     if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
-        if [ -z "$MEM_SNAP" ]; then
+        if [[ -z "${MEM_SNAP}" ]]; then
            splog "Error: VMSNAPSHOT_WITH_CHECKPOINT is set but checkpoint snapshot not found"
            exit 1
         fi
     fi
-    splog "snapList: ${snapList[@]}"
+    splog "snapList: ${snapList[*]}"
     finish=1
-    for snap in ${snapList[@]}; do
+    for snap in "${snapList[@]}"; do
         tb=$(date +%s%N)
-        splog "BEGIN snapshot $snap ($tb)"
-        volume="${snap%-$SNAP_ID}"
-        [ "${volume%-iso}" = "$volume" ] && mode="rw" || mode="$READONLY_MODE"
-        storpoolVolumeDetach "$volume" "force" "$VMHOST" "all"
-        storpoolVolumeInfo "$volume"
+        splog "BEGIN snapshot ${snap} (${tb})"
+        volume="${snap%"-${SNAP_ID}"}"
+        [[ "${volume%-iso}" == "${volume}" ]] && mode="rw" || mode="${READONLY_MODE}"
+        storpoolVolumeDetach "${volume}" "force" "${VMHOST}" "all"
+        storpoolVolumeInfo "${volume}"
         OLD_SIZE_M=$((V_SIZE/1024/1024))
-        if [ "$V_TYPE" = "CDROM"  ]; then
-            mode="$READONLY_MODE"
+        if [[ "${V_TYPE}" == "CDROM" ]]; then
+            mode="${READONLY_MODE}"
         fi
         tmpVolume="${volume}-${SP_TMP}"
-        storpoolRetry volume "$volume" rename "$tmpVolume" >/dev/null || finish=0
-        storpoolSnapshotClone "$snap" "$volume" "$V_TEMPLATE_NAME" || finish=0
-        storpoolVolumeInfo "$volume"
+        storpoolRetry volume "${volume}" rename "${tmpVolume}" >/dev/null || finish=0
+        storpoolSnapshotClone "${snap}" "${volume}" "${V_TEMPLATE_NAME}" || finish=0
+        storpoolVolumeInfo "${volume}"
         NEW_SIZE_M=$((V_SIZE/1024/1024))
-        if [ $OLD_SIZE_M -ne $NEW_SIZE_M ]; then
+        if [[ "${OLD_SIZE_M}" -ne "${NEW_SIZE_M}" ]]; then
             if boolTrue "UPDATE_ONE_DISK_SIZE"; then
-                if [ -n "${vmVolumesMap["$volume"]}" ]; then
-                    DISK_ID="${vmVolumesMap[$volume]}"
-                    onedb change-body vm --id $VM_ID "/VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE" $NEW_SIZE_M
-                    splog "onedb change VM_ID:$VM_ID DISK_ID:$DISK_ID SIZE:$NEW_SIZE_M (OLD_SIZE:$OLD_SIZE_M)($?)"
+                if [[ -n "${vmVolumesMap["${volume}"]}" ]]; then
+                    DISK_ID="${vmVolumesMap[${volume}]}"
+                    onedb change-body vm --id "${VM_ID}" "/VM/TEMPLATE/DISK[DISK_ID=${DISK_ID}]/SIZE" "${NEW_SIZE_M}"
+                    splog "onedb change VM_ID:${VM_ID} DISK_ID:${DISK_ID} SIZE:${NEW_SIZE_M} (OLD_SIZE:${OLD_SIZE_M})($?)"
                 else
-                    splog "vmVolumesMap[$volume] not found"
+                    splog "vmVolumesMap[${volume}] not found"
                 fi
-            elif [ $OLD_SIZE_M -gt $NEW_SIZE_M ]; then
+            elif [[ "${OLD_SIZE_M}" -gt "${NEW_SIZE_M}" ]]; then
                 splog "VM volume is +$((OLD_SIZE_M - NEW_SIZE_M))MB than snapshot. Inflating..."
-                storpoolVolumeResize "$volume" "${OLD_SIZE_M}M"
+                storpoolVolumeResize "${volume}" "${OLD_SIZE_M}M"
             fi
         else
-            splog "$tmpVolume=$OLD_SIZE_M $volume=$NEW_SIZE_M"
+            splog "${tmpVolume}=${OLD_SIZE_M} ${volume}=${NEW_SIZE_M}"
         fi
-        storpoolVolumeAttach "$volume" "$VMHOST" "$mode"
-        
-        VM_DISK_SP_QOSCLASS="${vmVolumesQcMap[$volume]}"
+        storpoolVolumeAttach "${volume}" "${VMHOST}" "${mode}"
+
+        VM_DISK_SP_QOSCLASS="${vmVolumesQcMap[${volume}]}"
 
         SP_QOSCLASS="${VM_DISK_SP_QOSCLASS:-${VM_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}}"
         debug_sp_qosclass
 
-        storpoolVolumeTag "$volume" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG};$VM_TAG;${VC_POLICY:+vc-policy}${SP_QOSCLASS:+qc}"
-        tmpVolumes+=("$tmpVolume")
+        storpoolVolumeTag "${volume}" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS}" "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy}${SP_QOSCLASS:+qc}"
+        tmpVolumes+=("${tmpVolume}")
         te=$(date +%s%N)
-        splog "END snapshot $snap ($te dt:$((te-tb)))"
+        splog "END snapshot ${snap} (${te} dt:$((te-tb)))"
     done
-    if boolTrue "finish"; then
-        for volume in ${tmpVolumes[@]}; do
-            storpoolVolumeDelete "$volume" "force" "snaps"
+    if boolTrue "finish" "${finish}"; then
+        for volume in "${tmpVolumes[@]}"; do
+            storpoolVolumeDelete "${volume}" "force" "snaps"
         done
     fi
     if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
         RET=$?
-        storpoolVolumeAttach "$MEM_SNAP" "$VMHOST" "ro" "snapshot"
-        MEM_LNK="/dev/storpool/$MEM_SNAP"
+        storpoolVolumeAttach "${MEM_SNAP}" "${VMHOST}" "ro" "snapshot"
+        MEM_LNK="/dev/storpool/${MEM_SNAP}"
         TDIR="$(mktemp -d)"
         VM_XML="${TDIR}/restore-${VM_ID}.xml"
         rCMD=$(cat <<EOF
- mkdir "$TDIR"
+ mkdir "${TDIR}"
  RET=\$?
- logger -t "${0##*/}_r[$$]" -- "mkdir $TDIR(\$RET)"
- [ \$RET -eq 0 ] || exit \$RET
- [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
- virsh --connect \$LIBVIRT_URI save-image-dumpxml "$MEM_LNK" >"$VM_XML"
+ logger -t "${0##*/}_r[$$]" -- "mkdir ${TDIR} (\$RET)"
+ [[ \${RET} -eq 0 ]] || exit \${RET}
+ [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
+ virsh --connect \${LIBVIRT_URI:-qemu:///system} save-image-dumpxml "${MEM_LNK}" >"${VM_XML}"
  RET=\$?
- logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml $MEM_LNK >$VM_XML (\$RET)"
- [ \$RET -eq 0 ] || exit \$RET
+ logger -t "${0##*/}_r[$$]" -- "virsh save-image-dumpxml ${MEM_LNK} >${VM_XML} (\$RET)"
+ [[ \${RET} -eq 0 ]] || exit \${RET}
  for i in 0 1 2; do
-   virsh --connect \$LIBVIRT_URI restore "$MEM_LNK" --xml $VM_XML &>>"$TDIR/restore-${VM_ID}-\${i}.log"
+   virsh --connect \${LIBVIRT_URI:-qemu:///system} restore "${MEM_LNK}" --xml "${VM_XML}" &>>"${TDIR}/restore-${VM_ID}-\${i}.log"
    RET=\$?
-   logger -t "${0##*/}_r[$$]" -- "[\$i] virsh restore $MEM_LNK --xml $VM_XML (\$RET)"
-   if [ \$RET -ne 0 ]; then
-       logger -t "${0##*/}_r[$$]" -- "[\$i] Error: \$(cat "$TDIR/restore-${VM_ID}-\${i}.log")"
+   logger -t "${0##*/}_r[$$]" -- "[\$i] virsh restore ${MEM_LNK} --xml ${VM_XML} (\$RET)"
+   if [[ \${RET} -ne 0 ]]; then
+       logger -t "${0##*/}_r[$$]" -- "[\$i] Error: \$(cat "${TDIR}/restore-${VM_ID}-\${i}.log")"
    else
        break
    fi
    sleep 0.5
  done
- rm -rf "$TDIR"
- logger -t "${0##*/}_r[$$]" -- "END $VM_ID (\$RET)"
- exit \$RET
+ rm -rf "${TDIR}"
+ logger -t "${0##*/}_r[$$]" -- "END ${VM_ID} (\$RET)"
+ exit "\${RET}"
 EOF
 )
-        splog "ssh $VMHOST virsh restore ..."
-        if $SSH "$VMHOST" "$rCMD" >"$TDIR/ssh.out" 2>"$TDIR/ssh.err"; then
-            splog "OK ssh $VMHOST ($?)"
+        splog "ssh ${VMHOST} virsh restore ..."
+        if ${SSH:-ssh} "${VMHOST}" "${rCMD}" >"${TDIR}/ssh.out" 2>"${TDIR}/ssh.err"; then
+            splog "OK ssh ${VMHOST} ($?)"
             RET=0
         else
-            splog "ssh $VMHOST failed! ($?)"
-            splog "DEBUG_OUT:$(cat "$TDIR/ssh.out")"
-            splog "DEBUG_ERR:$(cat "$TDIR/ssh.err")"
+            splog "ssh ${VMHOST} failed! ($?)"
+            splog "DEBUG_OUT:$(cat "${TDIR}/ssh.out"||true)"
+            splog "DEBUG_ERR:$(cat "${TDIR}/ssh.err"||true)"
             RET=1
         fi
-        storpoolVolumeDetach "$MEM_SNAP" "" "$VMHOST"
-        if [ $RET -ne 0 ]; then
-            splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID Failed! ($RET)"
-            exit $RET
+        storpoolVolumeDetach "${MEM_SNAP}" "" "${VMHOST}"
+        if [[ "${RET}" -ne 0 ]]; then
+            splog "END VM_ID=${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID} Failed! (${RET})"
+            exit "${RET}"
         fi
-        rm -rf "$TDIR"
+        rm -rf "${TDIR}"
     fi
-    splog "END VM_ID=$VM_ID VMHOST=$VMHOST SNAP_ID=$SNAP_ID"
+    splog "END VM_ID=${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID}"
     exit 0
 else
     splog "[CONTINUE]"
