handle the exit status of system datastore transfer

diff --git a/tm/storpool/mv b/tm/storpool/mv
--- a/tm/storpool/mv
+++ b/tm/storpool/mv
@@ -252,13 +252,20 @@ if [ "$DS_TEMPLATE_TYPE" = "SYSTEM_DS" ]; then
 set -e -o pipefail
 if [ -d "$SRC_PATH" ]; then
   logger -t "tm_sp_mv_r[\$\$]" -- "$TAR -C $SRC_DS_DIR --sparse -cf - $SRC_VM_DIR | $SSH $DST_HOST '$TAR -C $DST_DIR --sparse -xf -'"
-  $TAR -C "$SRC_DS_DIR" --sparse -cf - "$SRC_VM_DIR" | $SSH "$DST_HOST" '$TAR -C "$DST_DIR" --sparse -xf -;logger -t "tm_sp_mv_r[\$\$]" -- "rDone \$? \\$?"'
-  logger -t "tm_sp_mv_r[\$\$]" -- "rm -rf $SRC_PATH"
-  rm -rf "$SRC_PATH"
+  $TAR -C "$SRC_DS_DIR" --sparse -cf - "$SRC_VM_DIR" | $SSH "$DST_HOST" '$TAR -C "$DST_DIR" --sparse -xf -'
+  ret=\$?
+  if [ \$ret -eq 0 ]; then
+      logger -t "tm_sp_mv_r[\$\$]" -- "rm -rf $SRC_PATH"
+      rm -rf "$SRC_PATH"
+  else
+      logger -t "tm_sp_mv_r[\$\$]" -- "Error copying data! ret:\$ret"
+  fi
 else
   logger -t "tm_sp_mv_r[\$\$]" -- "Nothing to transfer: $SRC_HOST:$SRC_PATH not found."
+  ret=0
 fi
- logger -t "tm_sp_mv_r[\$\$]" -- "END"
+logger -t "tm_sp_mv_r[\$\$]" -- "END $VM_ID (\$ret)"
+exit \$ret
 EOF
 )
                     splog "Transfering $SRC_HOST:$SRC_PATH to $DST_HOST:$DST_DIR/$SRC_VM_DIR"
