refactor to use globalId
Change-Id: I160edfed6953ee1144c9302ab29c8f60fb71b72d
Signed-off-by: Anton Todorov <a.todorov@storpool.com>

diff --git a/tm/storpool/postmigrate b/tm/storpool/postmigrate
--- a/tm/storpool/postmigrate
+++ b/tm/storpool/postmigrate
@@ -36,13 +36,16 @@ TEMPLATE="$6"
 SYSTEM_MAD="$7"
 
 TM_PATH="$(dirname "${0}")"
+
 #shellcheck source=tm/storpool/storpool_common.sh
 source "${TM_PATH}/storpool_common.sh"
 
 if [[ ! -t 0 ]]; then
-    tmpxml="$(mktemp -t "postmigrate-${VM_ID}-XXXXXXXX")"
-    trapAdd "rm -rf \"${tmpxml}\""
-    cat > "${tmpxml}"
+    tmpxml="$(mktemp --tmpdir "postmigrate-${VM_ID}-XXXXXXXX")"
+    trapAdd APPEND "rm -rf \"${tmpxml}\""
+    # TEMPLATE_64 is for compatibility with migrate_other()
+    TEMPLATE_64="$(tee "${tmpxml}" || true)"
+    export TEMPLATE_64
     if [[ -s "${tmpxml}" ]]; then
         SYSTEM_MAD="$6"
         TEMPLATE="${tmpxml}"
@@ -54,6 +57,12 @@ if [[ "${SYSTEM_MAD:0:8}" == "storpool" ]]; then
         splog "[D] SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID} SYSTEM_MAD=${SYSTEM_MAD} (exit)"
     fi
     exit 0
+fi
+
+if boolTrue "MULTICLUSTER"; then
+    oneHostInfo "${SRC_HOST}"
+    DO_MULTICLUSTER=1
+    DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
 fi
 
 splog "SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID} SYSTEM_MAD=${SYSTEM_MAD}"
@@ -71,28 +80,37 @@ oneTemplateInfo "${TEMPLATE}"
 #-------------------------------------------------------------------------------
 # Detach storpool volumes
 #-------------------------------------------------------------------------------
-json=
+json=""
 for i in "${!DISK_ID_ARRAY[@]}"; do
-    if [[ "${DISK_TM_MAD_ARRAY[i]}" == "storpool" ]]; then
-        DISK_ID="${DISK_ID_ARRAY[i]}"
+    DISK_ID="${DISK_ID_ARRAY[i]}"
+    if [[ "${DISK_TM_MAD_ARRAY[i]:0:8}" == "storpool" ]]; then
         DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
         if [[ -n "${DISK_SOURCE}" ]]; then
-            DST_PATH="${VM_PATH}/disk.${DISK_ID}"
             SP_VOL="${DISK_SOURCE##*/}"
             if boolTrue "DISK_CLONE_ARRAY[i]"; then
-                SP_VOL+="-${VM_ID}-${DISK_ID_ARRAY[i]}"
+                SP_VOL+="-${VM_ID}-${DISK_ID}"
+                disk_type="nonpersistent"
             elif [[ "${DISK_TYPE_ARRAY[i]}" == "CDROM" ]]; then
-                # backward compatibility /clean up/
-                storpoolVolumeDetach "${SP_VOL}" "" "${SRC_HOST}" "none" "${DISK_READONLY_ARRAY[i]}"
-                SP_VOL+="-${VM_ID}-${DISK_ID_ARRAY[i]}"
+#                # backward compatibility /clean up/
+#                if kvGetUid "${SP_VOL}"; then
+#                    splog "BCK VM ${VM_ID} DISK ${DISK_ID} ${SP_VOL} ${SP_UID} RO:${DISK_READONLY_ARRAY[i]}"
+#                    storpoolDetach "${SP_UID}" "" "${SRC_HOST}" "none" "${DISK_READONLY_ARRAY[i]}"
+#                fi
+                SP_VOL+="-${VM_ID}-${DISK_ID}"
+                disk_type="cdrom"
+            else
+                disk_type="persistent"
             fi
-            [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
+            kvGetUid "${SP_VOL}" fatal
+            [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}" || true)"
             [[ -z "${json}" ]] || json+=","
-            json+="$(storpoolVolumeJsonHelper "${SP_VOL}" "${SRC_CLIENT}" "detach" "force" "${DISK_READONLY_ARRAY[i]}")"
-
+            json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force" "${DISK_READONLY_ARRAY[i]}" || true)"
+            if boolTrue "DEBUG_MIGRATE_LIVE"; then
+                splog "VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} ${disk_type} detach ${SRC_CLIENT}"
+            fi
         else
             if boolTrue "DEBUG_MIGRATE_LIVE"; then
-                splog "[D] skip volatile disk for ${DS_ID}/${VM_ID}/disk.${DISK_ID}"
+                splog "skip volatile disk for ${DS_ID}/${VM_ID}/disk.${DISK_ID} (no DISK/SOURCE)"
             fi
         fi
     fi
@@ -103,28 +121,34 @@ if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
     # Detach volatile disk volumes
     #-------------------------------------------------------------------------------
     for i in "${!DISK_ID_ARRAY[@]}"; do
+        DISK_ID="${DISK_ID_ARRAY[i]}"
         if [[ -z "${DISK_TM_MAD_ARRAY[i]}" ]] || [[ -z "${DISK_SOURCE_ARRAY[i]}" ]]; then
-            FORMAT="${DISK_FORMAT_ARRAY[i]:-raw}"
-            if [[ "${DISK_TYPE_ARRAY[i]}" == "swap" ]]; then
-                FORMAT="swap"
-            fi
-            SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID_ARRAY[i]}-${FORMAT}"
-            DST_PATH="${VM_PATH}/disk.${DISK_ID_ARRAY[i]}"
-            export DST_PATH  #  TBD: remove
+            SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
+            disk_type="volatile"
             [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
+            kvGetUid "${SP_VOL}" fatal
             [[ -z "${json}" ]] || json+=","
-            json+="$(storpoolVolumeJsonHelper "${SP_VOL}" "${SRC_CLIENT}" "detach" "force")"
+            json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
+            if boolTrue "DEBUG_MIGRATE_LIVE"; then
+                splog "[D] VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} ${disk_type} detach ${SRC_CLIENT}"
+            fi
          fi
     done
+
+    [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
 
     #-------------------------------------------------------------------------------
     # Detach context ISO volume
     #-------------------------------------------------------------------------------
     if [[ -n "${CONTEXT_DISK_ID}" ]]; then
-        SP_VOL="${ONE_PX}-sys-${VM_ID}-${CONTEXT_DISK_ID}-iso"
-        [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
+        DISK_ID="${CONTEXT_DISK_ID}"
+        SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
+        kvGetUid "${SP_VOL}" fatal
         [[ -z "${json}" ]] || json+=","
-        json+="$(storpoolVolumeJsonHelper "${SP_VOL}" "${SRC_CLIENT}" "detach" "force")"
+        json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
+        if boolTrue "DEBUG_MIGRATE_LIVE"; then
+            splog "[D] VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} detach ${SRC_CLIENT}"
+        fi
     fi
 
     #-------------------------------------------------------------------------------
@@ -132,9 +156,12 @@ if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
     #-------------------------------------------------------------------------------
     if [[ -n "${T_OS_NVRAM}" ]]; then
         SP_VOL="${ONE_PX}-sys-${VM_ID}-NVRAM"
-        [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
+        kvGetUid "${SP_VOL}" fatal
         [[ -z "${json}" ]] || json+=","
-        json+="$(storpoolVolumeJsonHelper "${SP_VOL}" "${SRC_CLIENT}" "detach" "force")"
+        json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
+        if boolTrue "DEBUG_MIGRATE_LIVE"; then
+            splog "[D] VM ${VM_ID} ${SP_VOL} ${SP_UID} detach ${SRC_CLIENT}"
+        fi
     fi
 
     #-------------------------------------------------------------------------------
@@ -145,7 +172,7 @@ if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
     fi
 fi
 
-storpoolRetry groupDetach "${json}"
+storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"
 
 MONITOR_TM_MAD=
 if ! boolTrue "DS_SHARED"; then
@@ -156,9 +183,9 @@ fi
 # Cleanup src VM files from the src host
 #-------------------------------------------------------------------------------
 if [[ "${DS_TM_MAD:0:8}" == "storpool" ]] && [[ "${SP_SYSTEM^^}" == "SSH" ]]; then
-    CMD="${SSH:-ssh} ${SRC_HOST} 'rm -rf ${VM_PATH}'"
-    splog "${CMD}"
-    exec_and_log "eval ${CMD}" "Error removing ${VM_PATH}"
+    RM_CMD="${SSH:-ssh} ${SRC_HOST} 'rm -rf ${VM_PATH}'"
+    splog "${RM_CMD}"
+    exec_and_log "eval ${RM_CMD}" "Error removing ${VM_PATH}"
 fi
 
 splog "END ${VM_ID}"
diff --git a/vmm/kvm/deploy-tweaks b/vmm/kvm/deploy-tweaks
--- a/vmm/kvm/deploy-tweaks
+++ b/vmm/kvm/deploy-tweaks
@@ -17,46 +17,83 @@
 #--------------------------------------------------------------------------- #
 
 export LOG_PREFIX="vmm"
-TMPDIR="$(mktemp -t -d deploy-tweaks-XXXXXXXX)"
-trap 'rm -rf "${TMPDIR}"' EXIT QUIT TERM HUP INT
+TMPDIR="$(mktemp --tmpdir -d deploy-tweaks-XXXXXXXX)"
+# shellcheck disable=SC2064
+trap "rm -rf '${TMPDIR}'" EXIT QUIT TERM HUP INT
 ERR_FILE="${TMPDIR}/error"
 
-if [[ -f ./config ]]; then
+if [[ -f "./config" ]]; then
     eval "$(grep -E 'DATASTORE_LOCATION|SCRIPTS_REMOTE_DIR' ./config || true)"
-elif [[ -f /var/lib/one/config ]]; then
+elif [[ -f "/var/lib/one/config" ]]; then
     eval "$(grep -E 'DATASTORE_LOCATION|SCRIPTS_REMOTE_DIR' /var/lib/one/config || true)"
 fi
 
-set -a
+set -a -o pipefail
 
-DRIVER_PATH="$(dirname "$0")"
-if [[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
+SCRIPT_PATH="$(dirname "$0")"
+if [[ -f "${SCRIPT_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
     # shellcheck source=/dev/null
-    source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc"
-elif [[ -f "${DRIVER_PATH}/kvmrc" ]]; then
+    source "${SCRIPT_PATH}/../../etc/vmm/kvm/kvmrc"
+elif [[ -f "${SCRIPT_PATH}/kvmrc" ]]; then
     # shellcheck source=/dev/null
-    source "${DRIVER_PATH}/kvmrc"
+    source "${SCRIPT_PATH}/kvmrc"
 fi
 # shellcheck source=/dev/null
-source "${DRIVER_PATH}/../../scripts_common.sh"
+source "${SCRIPT_PATH}/../../scripts_common.sh"
 
-if [[ -f "${DRIVER_PATH}/../../addon-storpoolrc" ]]; then
+if [[ -f "${SCRIPT_PATH}/../../addon-storpoolrc" ]]; then
     # shellcheck source=addon-storpoolrc
-    source "${DRIVER_PATH}/../../addon-storpoolrc"
+    source "${SCRIPT_PATH}/../../addon-storpoolrc"
 fi
 
 for var in ONE_PX NVRAM_TEMPLATE_PATH TMPDIR ERR_FILE; do
     [[ -z "${!var}" ]] || export "${var?}"
 done
 
+function oneCallXml()
+{
+    local _CALL="$1" _METHOD="$2" _ID="$3" _OUT_FILE="$4"
+    local _ERR_FILE="${TMPDIR}/${_CALL}-${_ID}.error"
+    local _TIMEFILE="${TMPDIR}/${_CALL}-${_ID}.time"
+    local _RET=1 _ONETRY=${ONE_CALL_RETRIES:-3} _TIME="" _XML_LINES=0
+    case "${_CALL}" in
+        onevm|onehost|onedatastore)
+            read -r -a _ONECMD <<< "${_CALL} ${_METHOD} ${ONE_ARGS:-} -x ${_ID}"
+            ;;
+        *)
+            echo "oneCallXml($*) Error: Unknown call'"
+            return 1
+            ;;
+    esac
+    while :; do
+        time ("${_ONECMD[@]}" >"${_OUT_FILE}" 2>"${_ERR_FILE}") 2>"${_TIMEFILE}"
+        _RET=$?
+        _TIME="$(tr '\n' ' ' <"${_TIMEFILE}" | tr '\t' ' ' ||true)"
+        _XML_LINES=$(wc -l "${_OUT_FILE}")
+        splog "${_ONECMD[*]} # ret=${_RET} time:${_TIME} xmlLines:${_XML_LINES}"
+        if [[ ${_RET} -eq 0 ]]; then
+            break
+        fi
+        if [[ ${_ONETRY} -lt 1 ]]; then
+            splog "'${_ONECMD[*]} ${_ID}' retry:${_ONETRY} Error: Timeout"
+            exit "${_RET}"
+        fi
+        _ONETRY=$((_ONETRY-1))
+        sleep 0.5
+    done
+    return "${_RET}"
+}
+
 if [[ -d /opt/storpool/python3/bin ]]; then
-    PATH="/opt/storpool/python3/bin:${PATH}"
-    export PATH
+    export PATH="/opt/storpool/python3/bin:${PATH}"
+    if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
+        splog "[D] appending /opt/storpool/python3/bin to PATH=${PATH}"
+    fi
 fi
 
 function splog()
 {
-    logger -t "vmm_sp_${0##*/}" "[$$] ${DEBUG_LINENO:+[${BASH_LINENO[-2]}]}$*"
+    logger -t "${LOG_PREFIX:-vmm}_sp_${0##*/}" "[$$] $*${DEBUG_LINENO:+ //[${BASH_LINENO[-2]}]}"
 }
 
 DEP_FILE="$1"
@@ -68,19 +105,16 @@ VM_XML="${TMPDIR}/vm.xml"
 
 cp -f "${DEP_FILE}" "${DEP_XML}"
 
-onevm show "${VM_ID}" -x >"${VM_XML}" 2>"${ERR_FILE}"
-ret=$?
-if [[ ${ret} -ne 0 ]]; then
-    errmsg="[deploy-tweaks] Can't get VM ${VM_ID} XML, VM_XML=${VM_XML}"
-    error_message "${errmsg}"
-    cat "${ERR_FILE}" >&2
-    splog "${errmsg}"
-    exit 255
+oneCallXml onevm show "${VM_ID}" "${VM_XML}"
+RET=$?
+if [[ ${RET} -ne 0 ]]; then
+    error_message "[E][deploy-tweaks] Error: Can't query VM ${VM_ID} (${TM_MAD},${DEPLOY_ID})"
+    exit "${_RET}"
 fi
 
 declare -a _XPATH_A _XPATH_QUERY
 _XPATH_A=(
-    "${DRIVER_PATH}/../../datastore/xpath.rb"
+    "${SCRIPT_PATH}/../../datastore/xpath.rb"
     "--stdin"
 )
 _XPATH_QUERY=(
@@ -89,36 +123,44 @@ _XPATH_QUERY=(
     "/VM/HISTORY_RECORDS/HISTORY[last()]/DS_ID"
 )
 
+sed '/\/>$/d' "${VM_XML}" >"${TMPDIR}/vmX.xml"
 unset i XPATH_ELEMENTS
-while IFS='' read -r -u "${xpathfh}" -d '' element; do
+while IFS='' read -r -u "${xfh}" -d '' element; do
     XPATH_ELEMENTS[i++]="${element}"
-done {xpathfh}< <( sed '/\/>$/d' "${VM_XML}" | "${_XPATH_A[@]}" "${_XPATH_QUERY[@]}" || true)
-exec {xpathfh}<&-
+done {xfh}< <("${_XPATH_A[@]}" <"${TMPDIR}/vmX.xml" "${_XPATH_QUERY[@]}" || true)
+exec {xfh}<&-
 unset i
-export DEPLOY_ID="${XPATH_ELEMENTS[i++]}"
-export TM_MAD="${XPATH_ELEMENTS[i++]}"
-export DS_ID="${XPATH_ELEMENTS[i++]}"
+DEPLOY_ID="${XPATH_ELEMENTS[i++]}"
+TM_MAD="${XPATH_ELEMENTS[i++]}"
+DS_ID="${XPATH_ELEMENTS[i++]}"
 
 if [[ -z "${DS_ID}" ]]; then
-    error_message "[deploy-tweaks] Can't get SYSTEM datastore ID for one-${VM_ID} VM_XML=${VM_XML} [${_XPATH_A[*]}] -- ${XPATH_ELEMENTS[*]}"
+    error_message "[E][deploy-tweaks] Can't get SYSTEM datastore ID for one-${VM_ID} (${TM_MAD},${DEPLOY_ID})"
     cat "${ERR_FILE}" >&2
     exit 255
 fi
 
 if [[ -d "${0}.d" ]]; then
-    while read -r -u "${hookfh}" hook; do
-        [[ -x "${0}.d/${hook}" ]] || continue
+    while read -r -u "${dtfh}" hook; do
+        [[ -x  "${hook}" ]] || continue
         cp -f "${DEP_XML}" "${TMPDIR}/deployment.xml"
-        splog "cp -f ${DEP_XML} ${TMPDIR}/deployment.xml ($?)"
-        splog "Calling ${0}.d/${hook} ${TMPDIR}/deployment.xml ${TMPDIR}/vm.xml ..."
-        "${0}.d/${hook}" "${TMPDIR}/deployment.xml" "${TMPDIR}/vm.xml" 2>"${ERR_FILE}"
         ret=$?
-        splog "${hook} (${ret})"
         if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
-            while read -r -u "${errfh}" line; do
-                splog "[D][${hook}]stderr:${line}"
+            splog "[D] cp -f ${DEP_XML} ${TMPDIR}/deployment.xml (${ret})"
+            splog "[D] Calling ${hook} ${TMPDIR}/deployment.xml ${TMPDIR}/vm.xml ..."
+        fi
+        "${hook}" "${TMPDIR}/deployment.xml" "${TMPDIR}/vm.xml" 2>"${ERR_FILE}"
+        ret=$?
+        splog "[I] ${hook} (${ret})"
+        if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
+            while read -r -u "${errfh}" errline; do
+                splog "[D] stderr:${errline} //${hook}"
             done {errfh}< <(cat "${ERR_FILE}" || true)
             exec {errfh}<&-
+            if [[ -n "${DDEBUG_DEPLOY_TWEAKS}" ]]; then
+                cp "${TMPDIR}/deployment.xml" "/tmp/deployment-${hook##*/}.xml"
+                cp "${TMPDIR}/vm.xml" "/tmp/vm-${hook##*/}.xml"
+            fi
         fi
         if [[ ${ret} -eq 0 ]]; then
             xmllint --noout "${TMPDIR}/deployment.xml" 2>"${ERR_FILE}"
@@ -127,32 +169,32 @@ if [[ -d "${0}.d" ]]; then
                 mv -f "${TMPDIR}/deployment.xml" "${DEP_XML}"
                 continue
             else
-                splog "Error: ${hook} succeeded but xmllint failed with exit code ${ret}"
+                splog "[W] Error: ${hook} succeeded but xmllint failed with exit code ${ret}"
             fi
         else
-            splog "${hook} failed with exit code ${ret}"
+            splog "[W] ${hook} failed with exit code ${ret}"
         fi
         if [[ -z "${DEBUG_DEPLOY_TWEAKS}" ]]; then
-            while read -r -u "${errfh}" line; do
-                splog "[D][${hook}]stderr:${line}"
-            done {errfh}< <(cat "${ERR_FILE}" || true)
-            exec {errfh}<&-
+            while read -r -u "${errfd}" errline; do
+                splog "[W] stderr:${errline}"
+            done {errfd}< <(cat "${ERR_FILE}" || true)
+            exec {errfd}<&-
         fi
-    done {hookfh}< <(ls -A "${0}.d" 2>"${ERR_FILE}" || true)
-    exec {hookfh}<&-
+    done {dtfh}< <(find "${0}.d/" -type f -o -type l || true)
+    exec {dtfh}<&-
 else
-    splog "Directory ${0}.d not found!"
+    splog "[W] Directory ${0}.d not found!"
 fi
 
-splog "Sending ${DEP_XML} to ${HOST} for ${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME} ..."
-DOMAIN_ID="$(${SSH:-ssh} "${HOST}" "${SCRIPTS_REMOTE_DIR:-/var/tmp/one}/vmm/kvm/deploy ${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME}" 2>>"${ERR_FILE}" <"${DEP_XML}")"
+splog "[I] Sending ${DEP_XML} to ${HOST} for ${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME} ..."
+DOMAIN_ID="$(${SSH:-ssh} "${HOST}" "\"${SCRIPTS_REMOTE_DIR:-/var/tmp/one}/vmm/kvm/deploy\" \"${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME}\"" < "${DEP_XML}" 2>>"${ERR_FILE}")"
 ret=$?
-splog "VM ${VM_ID} deploy on ${HOST} returned (${ret}) DOMAIN_ID=${DOMAIN_ID}"
+splog "VM ${VM_ID} deploy on ${HOST} DOMAIN_ID=${DOMAIN_ID} (${ret})"
 
 if [[ ${ret} -eq 0 ]]; then
     echo "${DOMAIN_ID}"
 else
-    error_message "[deploy-tweaks] VM ${VM_ID} could not create domain from ${DEP_XML}"
+    error_message "[deploy-tweaks] VM ${VM_ID} could not create domain from ${DEP_FILE}"
     cat "${ERR_FILE}" >&2
     exit 255
 fi
